### ISSUE TITLE
No need for character-count limit on topic page

### ISSUE THREAD

**Issue by cfarquharson** [canada-ca/design-system-systeme-conception#104]
While I think the character count feature is awesome on content pages, I don't think it makes sense on a 1-2 line doormat on a topic page.  It causes all topic's navigation to push down on the page and creates a very odd visual.  Given the limited value of the doormat and the limited amount of words in a doormat, I don't think pushing the navigation down just to improve readability of a one (or two sentences) is value worth it.

![screenshot-wordwrap](https://user-images.githubusercontent.com/2319199/86820893-87f97780-c03e-11ea-970f-4541e52edefc.PNG)

**Comment by delisma** [comment]
@cfarquharson IMHO I would prefer a better readability experience than a better scrolling experience. But I don't have any data to say if it's a common preferences.

**Comment by jmealing** [comment]
So, consider this a first experiment into getting the constraint site-wide for so that can have it where it will help the most, on "content pages". 

Once the new short, chunky h1 is sitewide, it definitely doesn't create a weird gap IMO. 

We haven't seen any negative impacts in testing on the slight "push down" of content in the topic description.

When you say doormat's being pushed down, I'm not sure what you mean. There is no impact on doormats whatsoever. It's not a **character count** restriction it's a character count **max-width**.

**Comment by Christopher-O** [comment]
@jmealing when you speak of short chunky H1, is that the stubby underline?  
To @cfarquharson point, unless the H1 will also be capped (which if it is, it will still be a longer width), then the H1 will be full width, then followed by a paragraph wrapped seemingly arbitrarily, then a Most requested section that is also full width (with the grey band).  Nothing else on the page is max-width characters since everything else is pretty much a grid, so without the image, it does look a bit odd.  
Granted I am unsure how that can be solved without risk of abuse to avoid proper character wrapping for other content on other pages that should be forced to be max-width.

**Comment by jmealing** [comment]
@Christopher-O Yes, the one in testing now

There's definitely a lot of to consider how it will look with upcoming experiments/changes to patterns, that's why we're starting small. We also are aware it doesn't work all that effectively in IE and "cuts" much sooner. 

Ideally, it seems like it should be handled by columns (like using col-md-8 to stop text from running the length of the screen) in the new templates for new content that goes live and avoid the small IE issue. 

The restriction, at the moment, would only be getting "P" tags, so you wouldn't have a short h1.

However, we do have a need for a site-wide solution that will impact existing content pages, without having to update the HTML in order to improve the reading experience immediately.

**Comment by jmealing** [comment]
@Christopher-O 

BTW the whole Wayfinding/Orientation project has been done with the new Topic templates with the restriction- and so far so good: https://wayfinding.alpha.experimentation.ca/en/landing/agriculture

**Comment by Christopher-O** [comment]
@jmealing thank you for the link.  however I'm a bit confused.  On the main agriculture link the teaser text is wrapped (though with the stubby I agree it does look okay), however on this page 
https://wayfinding.alpha.experimentation.ca/en/landing/agricultural-programs-and-services 
that is also in the new design, the teaser text is not wrapped and goes full width.

**Comment by jmealing** [comment]
@Christopher-O  Didn't meant to imply everything was all done and perfect here - it's a work in progress. Some of the site-wide CSS got mucked up with Drupal updates. There also may be some not-updated-to-the-new-topic because they were imported, but didn't fall in the scope of testing.

**Comment by cfarquharson** [comment]
@jmealing I think that agriculture page demonstrates why the wrapping of a single sentence on a topic page is not good.  

I looks like it ends with the word 'Food' because only the word "Policy." is on the following line.  Again, I think the restriction of characters on a content page is good, but I don't think it should be this way on a topic page.

![wrap](https://user-images.githubusercontent.com/2319199/86979002-046e8200-c135-11ea-9dfb-9a358771e945.PNG)

**Comment by jmealing** [comment]
@cfarquharson Orphan text can happen under any circumstance easily on the web, even with using other methods of restriction, like a col-md-8, etc. We do have alpha CSS for "no break" text when needed, like "Food Policy" needing to be together. It's originally designed for phone numbers and email addresses so they stay together.

I feel the restriction to stop the text from going full-screen length has way more benefit on readability than harm. We're eager to work toward the go-ahead for site-wide implementation on p tags (to deal with the biggest issue/greatest benefit on content pages). If a few words in a topic intro sentence get orphaned over the huge site-wide benefit of readability until someone goes back in and either update their intro text, or adds a no break class? I can totally live with that.

So for the moment, we'll have to agree to disagree.

**Comment by patlaj** [comment]
The other thing is that if we did make an exception for topic pages, it would make it harder to get it applied consistently elsewhere. We'd have to explain why it was OK in this case but not others. People would see how it was applied on topic pages and think it'd be ok to do it in their particular circumstance. 

Easier to get adoption when there's a consistent rule.
