### ISSUE TITLE
Inflexible design for 'Featured' section in new topic pattern

### ISSUE THREAD

**Issue by cfarquharson** [canada-ca/design-system-systeme-conception#106]
The guidance for the 'Featured' section on the new topic page https://design.canada.ca/coded-layout/theme_topic_guidance.html  says "The design of this section is flexible. You can modify it to suit your needs." yet it doesn't seem that is actually is flexible.  If you remove the featured entirely, you get a large area of dead white space that matches the height of the social media stacking on the right.  If you need to add more that one featured item, there is no room (or guidance on how to do that). 
![screenshot-featured](https://user-images.githubusercontent.com/2319199/86822123-115d7980-c040-11ea-9a0d-c9a1042ed09b.PNG)

Is there a reason it wouldn't be more like this? https://test.canada.ca/cra/templates/topic.html

**Comment by jmealing** [comment]
The updates we're making to the guidance should make this more clear about the flexibility (switching the socials to being inline).

Your example with 3 features is fine, but this template uses the single contextual promo which has shown to be more ideal in testing. Less promotion is better, especially when it's specific and targetted for the page - I believe Lisa shared that research deck with you.

In the future, when showing variations, we want to build that directly into the actual component page. Main templates would show "standard" and then you can go off and see the code variations available for each section: https://design.canada.ca/common-design-patterns/feature-tiles.html

**Comment by quidampepin** [comment]
In my mind, saying that it's flexible also meant: the exact presentation of that whole section is not mandated by policy. If you want to tweak the code for yourself and do something entirely different for that section, it's up to you - the version we're recommending is the one for which we provide the code, but you're not limited to it. For example, if you want to add Twitter feed there instead (for example), we're not recommending it and we're not providing this variation here (because we don't think it would serve a real user task - people follow Twitter on Twitter...), but doing so wouldn't be against the guidance.
